# Generated by Django 5.0 on 2024-05-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Services',
        ),
    ]
