# Generated by Django 5.0 on 2024-05-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Portfolio',
        ),
    ]
