# Generated by Django 5.0 on 2024-05-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_rename_services_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Service',
        ),
    ]
