# Generated by Django 5.0 on 2024-06-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_rename_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cus_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
