# Generated by Django 5.0 on 2024-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_service_cus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cus_email',
            field=models.EmailField(max_length=50),
        ),
    ]
